---
 - hosts: 172.16.3.3
   connection: local

   tasks:
     - name: reboot
       ios_command:
        commands:
         - reload in 30
         - y
        wait_for:
        - result[0] contains "Proceed with reload"
        provider: "{{ cli }}"
