---
- name: reboot cisco network devices
  hosts: 172.16.3.3
  connection: network_cli
  gather_facts: no

  tasks:
   - name: reboot
     ios_command:
               commands:
                  - command: "reload"
                    prompt: '[confirm]'
                    answer: "\r"
            
