---
 - hosts: 172.16.3.3
   connection: local

   tasks:
     - name: reboot
       ios_command:
         commands: 
          - command: "reload\n"
            prompt: 'Proceed with reload? [confirm]'
            answer: "\r"
       
